Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/IndentationConsistency:
  EnforcedStyle: rails
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Style/DotPosition:
  EnforcedStyle: trailing
Metrics/LineLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 12
Metrics/AbcSize:
  Max: 20
